name: Deploy Infra AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      SUBNET_ID: "subnet-096db494d1b21d5b1"
      SECURITY_GROUP_ID: "sg-0d25e52a9054cf0c7"
    
      # Variables para Terraform
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: "" # Se seteará en runtime con $KEY_NAME
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var "access_key=$AWS_ACCESS_KEY_ID" \
            -var "secret_key=$AWS_SECRET_ACCESS_KEY" \
            -var "region=$AWS_DEFAULT_REGION" \
            -var "key_name=$KEY_NAME" \
            -var "domain_name=${{ secrets.DOMAIN_NAME }}"


      - name: Cleanup
        if: failure() || cancelled()
        run: |
          if [ -n "$INSTANCE_ID" ]; then
            aws ec2 terminate-instances --instance-ids $INSTANCE_ID
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
          fi
          if [ -n "$AMI_ID" ]; then
            SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query "Images[0].BlockDeviceMappings[0].Ebs.SnapshotId" --output text)
            aws ec2 deregister-image --image-id $AMI_ID
            aws ec2 delete-snapshot --snapshot-id $SNAPSHOT_ID
          fi
          aws ec2 delete-key-pair --key-name $KEY_NAME
