name: pruebas
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
      SUBNET_ID: "subnet-096db494d1b21d5b1"      # Reemplazar por tu Subnet pública
      SECURITY_GROUP_ID: "sg-0d25e52a9054cf0c7" # Reemplazar por tu Security Group
      REGION: "us-east-1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.10.0"

      - name: Create SSH folder
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Generate temporary key pair
        run: |
          aws ec2 delete-key-pair --key-name temp-gha-key || true
          aws ec2 create-key-pair --key-name temp-gha-key \
            --query "KeyMaterial" --output text > ~/.ssh/temp-key.pem
          chmod 400 ~/.ssh/temp-key.pem
          echo "KEY_NAME=temp-gha-key" >> $GITHUB_ENV
          echo "PRIVATE_KEY_PATH=/home/runner/.ssh/temp-key.pem" >> $GITHUB_ENV

      - name: Packer Init
        working-directory: packer
        run: packer init ami.pkr.hcl

      - name: Build AMI (con Ansible inside Packer)
        working-directory: packer
        run: |
          packer build \
            -var "key_name=$KEY_NAME" \
            -var "private_key_path=$PRIVATE_KEY_PATH" \
            -var "subnet_id=$SUBNET_ID" \
            -var "security_group_id=$SECURITY_GROUP_ID" \
            ami.pkr.hcl

      - name: Cleanup key pair
        if: always()
        run: aws ec2 delete-key-pair --key-name $KEY_NAME
