name: pruebas
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      EC2_PUBLIC_IP: "3.92.208.127" # La IP pública de tu instancia
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.10.0"

      - name: Packer Init
        working-directory: packer
        run: |
          packer init ami.pkr.hcl

      - name: Create SSH folder
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Write SSH key
        run: |
          echo "${{ env.EC2_SSH_KEY }}" > ~/.ssh/my-key.pem
          chmod 400 ~/.ssh/my-key.pem

      - name: Build AMI
        working-directory: packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
        run: |
          packer build ami.pkr.hcl


      - name: Get AMI ID
        id: ami
        run: |
          AMI_ID=$(jq -r '.builds[0].artifact_id' packer/manifest.json | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "TF_VAR_ami_id=$AMI_ID" >> $GITHUB_ENV
          echo "AMI_ID=$AMI_ID"

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass


      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ env.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > inventory.ini
          echo "${{ env.EC2_PUBLIC_IP }} ansible_ssh_private_key_file=~/.ssh/my-key.pem ansible_user=ubuntu" >> inventory.ini
          cat inventory.ini

      - name: Test Ansible connectivity
        run: ansible -i inventory.ini -m ping all

      - name: Terminate EC2 instance
        if: always()
        run: |
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID
          aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID

      - name: Deregister AMI
        if: always()
        run: |
          SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query "Images[0].BlockDeviceMappings[0].Ebs.SnapshotId" --output text)
          aws ec2 deregister-image --image-id $AMI_ID
          aws ec2 delete-snapshot --snapshot-id $SNAPSHOT_ID
