name: ver estado de terraform
on:
  workflow_dispatch:

jobs:
  tfstate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Terraform State List
        run: terraform state list
